### ISSUE TITLE
Segmentation fault on visiting youtube.com

### ISSUE THREAD

**Issue by sewnie** [luakit/luakit#1079]
**Current Behavior:**
Segmentation fault when visiting youtube.com

**Desired Behavior:**
I can view youtube.com

**How can we reproduce it (step by step):**
1. `luakit youtube.com`
2. Observe

**Environment:**

Linux Distribution & Version: Alpine Linux edge
Output of `luakit --version`:
```
luakit 5cff4d87
  built with: webkit 2.42.4 (installed version: 2.42.5)
                 GTK 3.24.38 
                GLIB 2.78.4 
                SOUP 3.4.4 
```

```
Thread 25 "send_thread" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 8641]
g_io_channel_write_chars (channel=0x6e6f6d6d6f630000, buf=0x7fff96dbbdf0 "K\001", count=8, bytes_written=0x0, error=0x0) at ../glib/giochannel.c:2214
warning: 2214   ../glib/giochannel.c: No such file or directory
(gdb) bt
#0  g_io_channel_write_chars (channel=0x6e6f6d6d6f630000, buf=0x7fff96dbbdf0 "K\001", count=8, bytes_written=0x0, error=0x0) at ../glib/giochannel.c:2214
#1  0x00005555555682d4 in ?? ()
#2  0x00007ffff013d391 in g_thread_proxy (data=0x7fffa1fc3fa0) at ../glib/gthread.c:831
#3  0x00007ffff7fb822e in start (p=0x7fff926021d0) at src/thread/pthread_create.c:207
#4  0x00007ffff7fba82f in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC
(gdb) 
```

**Comment by c0dev0id** [comment]
Youtube works for me, but I think this may the same problem as reported in the https://github.com/luakit/luakit/issues/1067 issue.

**Comment by sewnie** [comment]
Duplicate of #1067
