### ISSUE TITLE
crashes after a few clicks (2012.09.13-r1) - possibly related to libjavascriptcoregtk-1.0.so.0

### ISSUE THREAD

**Issue by johnchristopher** [luakit/luakit#179]
I am running minimal ubuntu 12.10 32 bits with awesome-wm. I compiled and installed luakit from sources (luakit 2012.09.13-r1-32-g993d814) without too much problems and without compilation special flags.

Everytime I start luakit and clik "Features" on the homepage and then "Quick start guide" luakit segfaults. When running from the cli I usually get a dBus error message:unable to connect to the running instance, aborting (could the dBus flag be the source of my problem ?)

Here is the backtrace from 'gdb luakit'

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()

(gdb) bt
#0  0x00000000 in ?? ()
#1  0xb6a9b55f in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#2  0xb63a321c in JSC::WeakBlock::visit(JSC::HeapRootVisitor&) () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#3  0xb63a120c in JSC::MarkedSpace::visitWeakSets(JSC::HeapRootVisitor&) () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#4  0xb6399ee0 in JSC::Heap::markRoots(bool) () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#5  0xb639aa67 in JSC::Heap::collect(JSC::Heap::SweepToggle) () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#6  0xb639ac2c in JSC::Heap::collectAllGarbage() () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#7  0xb6a54b7b in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#8  0xb6a54e35 in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#9  0xb7157702 in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#10 0xb7157775 in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#11 0xb7aee1ab in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#12 0xb5a046bf in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#13 0xb5a039e3 in g_main_context_dispatch () from /lib/i386-linux-gnu/libglib-2.0.so.0
#14 0xb5a03d80 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#15 0xb5a041db in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
#16 0xb5e953a0 in gtk_main () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#17 0x08053147 in main (argc=1, argv=0xbffffc24) at luakit.c:189
```

Always the same error message and it's reproductible.

Not sure if it helps but uzbl and midori also crashes in the same way (but not at the same time or pages). Here's a typical uzbl crash:

```
#0  0x00000000 in ?? ()
#1  0xb6a9b55f in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#2  0xb5fb521c in JSC::WeakBlock::visit(JSC::HeapRootVisitor&) () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#3  0xb5fb320c in JSC::MarkedSpace::visitWeakSets(JSC::HeapRootVisitor&) () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#4  0xb5fabee0 in JSC::Heap::markRoots(bool) () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#5  0xb5faca67 in JSC::Heap::collect(JSC::Heap::SweepToggle) () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#6  0xb5facc2c in JSC::Heap::collectAllGarbage() () from /usr/lib/libjavascriptcoregtk-1.0.so.0
#7  0xb6a54b7b in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#8  0xb6a54e35 in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#9  0xb7157702 in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#10 0xb7157775 in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#11 0xb7aee1ab in ?? () from /usr/lib/libwebkitgtk-1.0.so.0
#12 0xb5c4b6bf in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#13 0xb5c4a9e3 in g_main_context_dispatch () from /lib/i386-linux-gnu/libglib-2.0.so.0
#14 0xb5c4ad80 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#15 0xb5c4b1db in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
#16 0xb646d3a0 in gtk_main () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#17 0x0804fc99 in ?? ()
#18 0xb59224d3 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#19 0x0804d001 in ?? ()
```

I mention this because it seems the problem lies with libjavascriptcoregtk-1.0.so.0.

What other kind of information would you like me to provide ?

**Comment by aidanholm** [comment]
This is fixed with the switch to WebKit 2.
