### ISSUE TITLE
Website data remove() segfault under some circumstances

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#343]
```
(gdb) backtrace
#0  0x00007f52b032f8be in lua_pushboolean () at /usr/lib/libluajit-5.1.so.2
#1  0x0000559f96af75ce in website_data_remove_finish (manager=<optimized out>, result=<optimized out>, wdrt=0x559f98922c80) at clib/luakit.c:506
#2  0x00007f52b0b46d53 in  () at /usr/lib/libgio-2.0.so.0
#3  0x00007f52b0b47776 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007f52b00dbb62 in WTF::RunLoop::performWork() () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#5  0x00007f52b00da839 in  () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#6  0x00007f52af0218c5 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#7  0x00007f52af021c88 in  () at /usr/lib/libglib-2.0.so.0
#8  0x00007f52af021fa2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#9  0x00007f52b1e0db25 in gtk_main () at /usr/lib/libgtk-3.so.0
#10 0x0000559f96aea855 in main (argc=<optimized out>, argv=<optimized out>) at luakit.c:225
```

**Comment by aidanholm** [comment]
Should be fixed at 1af45f23
