### ISSUE TITLE
ASAN: Memory leak

### ISSUE THREAD

**Issue by RootUp** [luakit/luakit#744]
Hi Team,

While fuzzing the master branch of luakit a memory leak was observed, below is the MSAN trace for your reference.

```c
==35865==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 96 byte(s) in 3 object(s) allocated from:
    #0 0x7f21ddbb4458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x7f21d8de5021 in bmalloc::Heap::Heap(bmalloc::HeapKind, std::lock_guard<bmalloc::Mutex>&) (/usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18+0xe91021)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f21ddbb4458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x7f217e4aa09d in acommon::DictInfoList::elements() const (/usr/lib/x86_64-linux-gnu/libaspell.so.15+0x3709d)
    #2 0x1b5f9b71473effff  (<unknown module>)

Indirect leak of 120 byte(s) in 3 object(s) allocated from:
    #0 0x7f21ddbb4458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x7f21d8de5001 in bmalloc::Heap::Heap(bmalloc::HeapKind, std::lock_guard<bmalloc::Mutex>&) (/usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18+0xe91001)

SUMMARY: AddressSanitizer: 248 byte(s) leaked in 7 allocation(s).
```

**Comment by aidanholm** [comment]
Thank you for reporting! This looks like it might be a leak in aspell or its dependant webkit2gtk, however, judging by the `DictInfoList::elements()` in the trace. Any chance you could provide more info?

**Comment by c0dev0id** [comment]
If you're looking at this again, the current development branch ist the branch named "develop", not master. Master is quite old.
